[2025-04-06T15:20:27.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_file_upload_dag.run_data_loading scheduled__2025-04-06T15:10:00+00:00 [queued]>
[2025-04-06T15:20:27.488+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_file_upload_dag.run_data_loading scheduled__2025-04-06T15:10:00+00:00 [queued]>
[2025-04-06T15:20:27.503+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-06T15:20:27.559+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_data_loading> on 2025-04-06 15:10:00+00:00
[2025-04-06T15:20:27.587+0000] {standard_task_runner.py:60} INFO - Started process 657 to run task
[2025-04-06T15:20:27.592+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_file_upload_dag', 'run_data_loading', 'scheduled__2025-04-06T15:10:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/gcs_fileupload_dag.py', '--cfg-path', '/tmp/tmpbc5cv_wn']
[2025-04-06T15:20:27.611+0000] {standard_task_runner.py:88} INFO - Job 214: Subtask run_data_loading
[2025-04-06T15:20:27.646+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-06T15:20:27.775+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_file_upload_dag.run_data_loading scheduled__2025-04-06T15:10:00+00:00 [running]> on host 360c490b0eef
[2025-04-06T15:20:27.969+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_file_upload_dag' AIRFLOW_CTX_TASK_ID='run_data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T15:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-06T15:10:00+00:00'
[2025-04-06T15:20:27.973+0000] {gcs_fileupload_dag.py:16} INFO - Calling data_loading from DAG...
[2025-04-06T15:20:27.975+0000] {logging_mixin.py:188} INFO - Starting data_loading...
[2025-04-06T15:20:28.383+0000] {logging_mixin.py:188} INFO - GIT API rate limit: 5000/5000
[2025-04-06T15:20:29.402+0000] {logging_mixin.py:188} INFO - Repository Ai-app-by-using-python already cloned. Skipping.
[2025-04-06T15:20:29.404+0000] {logging_mixin.py:188} INFO - Repository MaxBrowser already cloned. Skipping.
[2025-04-06T15:26:17.547+0000] {logging_mixin.py:188} WARNING - Processing portfolio: 0it [00:00, ?it/s]
[2025-04-06T15:26:17.555+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.565+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.568+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.569+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:17.570+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:17.571+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/README.md
[2025-04-06T15:26:17.574+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.577+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.583+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.585+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:17.591+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:17.598+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/mountains-min.jpg
[2025-04-06T15:26:17.610+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/react-2.svg
[2025-04-06T15:26:17.612+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/clouds-min.png
[2025-04-06T15:26:17.614+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/calculator_image.png
[2025-04-06T15:26:17.614+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/css-3.svg
[2025-04-06T15:26:17.615+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/favicon-16x16.png
[2025-04-06T15:26:17.616+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/loginform_pic.png
[2025-04-06T15:26:17.618+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/linkedInlogo.png
[2025-04-06T15:26:17.621+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/Sandwichbar_pic.png
[2025-04-06T15:26:17.623+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/Man Jacket Transparent.png
[2025-04-06T15:26:17.624+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/html-1.svg
[2025-04-06T15:26:17.626+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/WeatherApp_pic.png
[2025-04-06T15:26:17.628+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/FilmBookingSystem_pic.png
[2025-04-06T15:26:17.634+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/logo-javascript.svg
[2025-04-06T15:26:17.637+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/images/python-5.svg
[2025-04-06T15:26:17.644+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.658+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.662+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.663+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:17.664+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:17.669+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.678+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.684+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:17.685+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:17.688+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:17.689+0000] {logging_mixin.py:188} WARNING - Processing portfolio: 3it [00:00, 21.38it/s]
[2025-04-06T15:26:17.690+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/HEAD
[2025-04-06T15:26:17.694+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/index
[2025-04-06T15:26:17.697+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/packed-refs
[2025-04-06T15:26:17.700+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/description
[2025-04-06T15:26:17.703+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/config
[2025-04-06T15:26:17.710+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:17.717+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/refs/heads/main
[2025-04-06T15:26:17.722+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/logs/HEAD
[2025-04-06T15:26:17.728+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:17.730+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/logs/refs/heads/main
[2025-04-06T15:26:17.733+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/objects/pack/pack-59f0562b361080e16623337b4881c9fceb50016f.idx
[2025-04-06T15:26:17.735+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/objects/pack/pack-59f0562b361080e16623337b4881c9fceb50016f.pack
[2025-04-06T15:26:17.743+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/pre-receive.sample
[2025-04-06T15:26:17.745+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:17.747+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:17.751+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/commit-msg.sample
[2025-04-06T15:26:17.760+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:17.768+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/update.sample
[2025-04-06T15:26:17.774+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/post-update.sample
[2025-04-06T15:26:17.778+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:17.780+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:17.781+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:17.782+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:17.782+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/pre-push.sample
[2025-04-06T15:26:17.783+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/hooks/pre-commit.sample
[2025-04-06T15:26:17.784+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/portfolio/.git/info/exclude
[2025-04-06T15:26:17.785+0000] {logging_mixin.py:188} WARNING - Processing portfolio: 20it [00:00, 84.69it/s]
[2025-04-06T15:26:17.793+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/portfolio
[2025-04-06T15:26:17.796+0000] {logging_mixin.py:188} INFO - Repository learning-python already cloned. Skipping.
[2025-04-06T15:26:18.717+0000] {logging_mixin.py:188} WARNING - Processing ToDo-List: 0it [00:00, ?it/s]
[2025-04-06T15:26:18.724+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:18.730+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:18.739+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:18.741+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:18.743+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:18.745+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/README.md
[2025-04-06T15:26:18.750+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:18.754+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:18.759+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:18.760+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:18.761+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:18.762+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/script.js
[2025-04-06T15:26:18.763+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/HEAD
[2025-04-06T15:26:18.765+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/index
[2025-04-06T15:26:18.766+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/packed-refs
[2025-04-06T15:26:18.774+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/description
[2025-04-06T15:26:18.776+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/config
[2025-04-06T15:26:18.777+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:18.778+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/refs/heads/main
[2025-04-06T15:26:18.780+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/logs/HEAD
[2025-04-06T15:26:18.783+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:18.797+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/logs/refs/heads/main
[2025-04-06T15:26:18.802+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/objects/pack/pack-ed0f3cad69c561517214c21b6a3aed9babcc24ce.idx
[2025-04-06T15:26:18.804+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/objects/pack/pack-ed0f3cad69c561517214c21b6a3aed9babcc24ce.pack
[2025-04-06T15:26:18.806+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/pre-receive.sample
[2025-04-06T15:26:18.808+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:18.808+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:18.810+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/commit-msg.sample
[2025-04-06T15:26:18.811+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:18.812+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/update.sample
[2025-04-06T15:26:18.813+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/post-update.sample
[2025-04-06T15:26:18.814+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:18.815+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:18.816+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:18.824+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:18.825+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/pre-push.sample
[2025-04-06T15:26:18.827+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/hooks/pre-commit.sample
[2025-04-06T15:26:18.829+0000] {logging_mixin.py:188} WARNING - Processing ToDo-List: 16it [00:00, 145.58it/s]
[2025-04-06T15:26:18.830+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/ToDo-List/.git/info/exclude
[2025-04-06T15:26:18.832+0000] {logging_mixin.py:188} WARNING - Processing ToDo-List: 18it [00:00, 159.02it/s]
[2025-04-06T15:26:18.840+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/ToDo-List
[2025-04-06T15:26:18.849+0000] {logging_mixin.py:188} INFO - Repository Real_Time_Voice_Translator_Web already cloned. Skipping.
[2025-04-06T15:26:24.236+0000] {logging_mixin.py:188} WARNING - Processing text_classifcation_with_attention: 0it [00:00, ?it/s]
[2025-04-06T15:26:24.247+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:24.251+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:24.256+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:24.257+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:24.258+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:24.259+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/README.md
[2025-04-06T15:26:24.260+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/HEAD
[2025-04-06T15:26:24.262+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/index
[2025-04-06T15:26:24.263+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/packed-refs
[2025-04-06T15:26:24.264+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/description
[2025-04-06T15:26:24.265+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/config
[2025-04-06T15:26:24.266+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:24.267+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/refs/heads/main
[2025-04-06T15:26:24.268+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/logs/HEAD
[2025-04-06T15:26:24.270+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:24.270+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/logs/refs/heads/main
[2025-04-06T15:26:24.272+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/objects/pack/pack-53da470091536fb64cdedd99e49714cb7dccf221.idx
[2025-04-06T15:26:24.279+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/objects/pack/pack-53da470091536fb64cdedd99e49714cb7dccf221.pack
[2025-04-06T15:26:24.280+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/pre-receive.sample
[2025-04-06T15:26:24.281+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:24.283+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:24.284+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/commit-msg.sample
[2025-04-06T15:26:24.285+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:24.286+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/update.sample
[2025-04-06T15:26:24.287+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/post-update.sample
[2025-04-06T15:26:24.288+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:24.291+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:24.292+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:24.293+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:24.294+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/pre-push.sample
[2025-04-06T15:26:24.294+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/hooks/pre-commit.sample
[2025-04-06T15:26:24.295+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/text_classifcation_with_attention/.git/info/exclude
[2025-04-06T15:26:24.296+0000] {logging_mixin.py:188} WARNING - Processing text_classifcation_with_attention: 18it [00:00, 326.07it/s]
[2025-04-06T15:26:24.299+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/text_classifcation_with_attention
[2025-04-06T15:26:24.302+0000] {logging_mixin.py:188} INFO - Repository voiceover already cloned. Skipping.
[2025-04-06T15:26:24.956+0000] {logging_mixin.py:188} WARNING - Processing crypto-pay: 0it [00:00, ?it/s]
[2025-04-06T15:26:24.959+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/HEAD
[2025-04-06T15:26:24.964+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/index
[2025-04-06T15:26:24.969+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/packed-refs
[2025-04-06T15:26:24.972+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/description
[2025-04-06T15:26:24.973+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/config
[2025-04-06T15:26:24.975+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:24.976+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/refs/heads/main
[2025-04-06T15:26:24.977+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/logs/HEAD
[2025-04-06T15:26:24.977+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:24.978+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/logs/refs/heads/main
[2025-04-06T15:26:24.979+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/objects/pack/pack-65cbfc2d2224bfcf9ff0ed0443803ceb0d4ce9d2.pack
[2025-04-06T15:26:24.979+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/objects/pack/pack-65cbfc2d2224bfcf9ff0ed0443803ceb0d4ce9d2.idx
[2025-04-06T15:26:24.981+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/pre-receive.sample
[2025-04-06T15:26:24.982+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:24.983+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:24.984+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/commit-msg.sample
[2025-04-06T15:26:24.985+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:24.985+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/update.sample
[2025-04-06T15:26:24.991+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/post-update.sample
[2025-04-06T15:26:24.994+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:24.995+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:24.996+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:24.997+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:24.998+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/pre-push.sample
[2025-04-06T15:26:24.999+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/hooks/pre-commit.sample
[2025-04-06T15:26:25.000+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/.git/info/exclude
[2025-04-06T15:26:25.000+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/README.md
[2025-04-06T15:26:25.001+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/docker-compose.yml
[2025-04-06T15:26:25.002+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/.gitignore
[2025-04-06T15:26:25.004+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/api_key/.dockerignore
[2025-04-06T15:26:25.022+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.033+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.042+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.045+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:25.046+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:25.078+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.089+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.101+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.103+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:25.110+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:25.112+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/api_key/Dockerfile
[2025-04-06T15:26:25.135+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.151+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.154+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.155+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:25.155+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:25.156+0000] {logging_mixin.py:188} WARNING - Processing crypto-pay: 21it [00:00, 106.45it/s]
[2025-04-06T15:26:25.161+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.184+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.198+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.199+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:25.200+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:25.205+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.210+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.218+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.219+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:25.221+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:25.257+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.288+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.300+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:25.302+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:25.304+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:25.306+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/README.md
[2025-04-06T15:26:25.308+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/package.json
[2025-04-06T15:26:25.308+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/.dockerignore
[2025-04-06T15:26:25.309+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/app.js
[2025-04-06T15:26:25.310+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/Dockerfile
[2025-04-06T15:26:25.311+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/api/middlewares.js
[2025-04-06T15:26:25.313+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/api/authController.js
[2025-04-06T15:26:25.314+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/api/authModel.js
[2025-04-06T15:26:25.315+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/crypto-pay/server/services/auth/api/authRoutes.js
[2025-04-06T15:26:25.319+0000] {logging_mixin.py:188} WARNING - Processing crypto-pay: 24it [00:00, 66.56it/s] 
[2025-04-06T15:26:25.326+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/crypto-pay
[2025-04-06T15:26:26.164+0000] {logging_mixin.py:188} WARNING - Processing SpeakEasy-ChatBot: 0it [00:00, ?it/s]
[2025-04-06T15:26:26.169+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.173+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.177+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.178+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:26.179+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:26.180+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/README.md
[2025-04-06T15:26:26.181+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/requirements.txt
[2025-04-06T15:26:26.184+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.188+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.192+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.193+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:26.194+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:26.195+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/HEAD
[2025-04-06T15:26:26.195+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/index
[2025-04-06T15:26:26.197+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/packed-refs
[2025-04-06T15:26:26.197+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/description
[2025-04-06T15:26:26.200+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/config
[2025-04-06T15:26:26.201+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:26.202+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/refs/heads/AIDS
[2025-04-06T15:26:26.204+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/logs/HEAD
[2025-04-06T15:26:26.205+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:26.206+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/logs/refs/heads/AIDS
[2025-04-06T15:26:26.208+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/objects/pack/pack-a4db57afe81535fb5000c54b4a9c2d624c327ea2.pack
[2025-04-06T15:26:26.209+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/objects/pack/pack-a4db57afe81535fb5000c54b4a9c2d624c327ea2.idx
[2025-04-06T15:26:26.211+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/pre-receive.sample
[2025-04-06T15:26:26.212+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:26.213+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:26.214+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/commit-msg.sample
[2025-04-06T15:26:26.215+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:26.216+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/update.sample
[2025-04-06T15:26:26.217+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/post-update.sample
[2025-04-06T15:26:26.218+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:26.219+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:26.220+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:26.221+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:26.222+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/pre-push.sample
[2025-04-06T15:26:26.223+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/hooks/pre-commit.sample
[2025-04-06T15:26:26.225+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.git/info/exclude
[2025-04-06T15:26:26.231+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.237+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.240+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.242+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:26.243+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:26.247+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.251+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.256+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:26.257+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:26.258+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:26.259+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/SpeakEasy-ChatBot/.github/workflows/python-app.yml
[2025-04-06T15:26:26.260+0000] {logging_mixin.py:188} WARNING - Processing SpeakEasy-ChatBot: 22it [00:00, 232.64it/s]
[2025-04-06T15:26:26.263+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/SpeakEasy-ChatBot
[2025-04-06T15:26:27.038+0000] {logging_mixin.py:188} WARNING - Processing codepad: 0it [00:00, ?it/s]
[2025-04-06T15:26:27.050+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.063+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.069+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.075+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:27.079+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:27.083+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/README.md
[2025-04-06T15:26:27.087+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/package.json
[2025-04-06T15:26:27.091+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.gitignore
[2025-04-06T15:26:27.092+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/server.js
[2025-04-06T15:26:27.097+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.114+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.123+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.124+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:27.125+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:27.126+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/package-lock.json
[2025-04-06T15:26:27.128+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/main.js
[2025-04-06T15:26:27.140+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.148+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.167+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:27.169+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:27.171+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:27.172+0000] {logging_mixin.py:188} WARNING - Processing codepad: 2it [00:00, 15.35it/s]
[2025-04-06T15:26:27.174+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/HEAD
[2025-04-06T15:26:27.175+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/index
[2025-04-06T15:26:27.178+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/packed-refs
[2025-04-06T15:26:27.179+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/description
[2025-04-06T15:26:27.182+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/config
[2025-04-06T15:26:27.184+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:27.185+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/refs/heads/main
[2025-04-06T15:26:27.190+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/logs/HEAD
[2025-04-06T15:26:27.196+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:27.201+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/logs/refs/heads/main
[2025-04-06T15:26:27.202+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/objects/pack/pack-8fdb65d4293c6720cc189f1baf38c61811eda3c8.pack
[2025-04-06T15:26:27.204+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/objects/pack/pack-8fdb65d4293c6720cc189f1baf38c61811eda3c8.idx
[2025-04-06T15:26:27.205+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/pre-receive.sample
[2025-04-06T15:26:27.206+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:27.208+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:27.209+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/commit-msg.sample
[2025-04-06T15:26:27.215+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:27.216+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/update.sample
[2025-04-06T15:26:27.217+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/post-update.sample
[2025-04-06T15:26:27.219+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:27.220+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:27.222+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:27.223+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:27.230+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/pre-push.sample
[2025-04-06T15:26:27.231+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/hooks/pre-commit.sample
[2025-04-06T15:26:27.232+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/codepad/.git/info/exclude
[2025-04-06T15:26:27.233+0000] {logging_mixin.py:188} WARNING - Processing codepad: 19it [00:00, 99.46it/s]
[2025-04-06T15:26:27.236+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/codepad
[2025-04-06T15:26:28.025+0000] {logging_mixin.py:188} WARNING - Processing aarinmahala: 0it [00:00, ?it/s]
[2025-04-06T15:26:28.030+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:28.034+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:28.039+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:28.040+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:28.041+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:28.044+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:28.047+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:28.050+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:28.051+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:28.052+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:28.055+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/Unconfirmed 929645.crdownload
[2025-04-06T15:26:28.056+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/im11.jpg
[2025-04-06T15:26:28.057+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/script.js
[2025-04-06T15:26:28.057+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/im1.jpg
[2025-04-06T15:26:28.058+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/HEAD
[2025-04-06T15:26:28.059+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/index
[2025-04-06T15:26:28.060+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/packed-refs
[2025-04-06T15:26:28.061+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/description
[2025-04-06T15:26:28.062+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/config
[2025-04-06T15:26:28.063+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:28.068+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/refs/heads/main
[2025-04-06T15:26:28.069+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/logs/HEAD
[2025-04-06T15:26:28.070+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:28.071+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/logs/refs/heads/main
[2025-04-06T15:26:28.072+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/objects/pack/pack-f3892bb5777262aacedfa289986fc151aeea249a.pack
[2025-04-06T15:26:28.072+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/objects/pack/pack-f3892bb5777262aacedfa289986fc151aeea249a.idx
[2025-04-06T15:26:28.073+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/pre-receive.sample
[2025-04-06T15:26:28.074+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:28.075+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:28.076+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/commit-msg.sample
[2025-04-06T15:26:28.077+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:28.077+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/update.sample
[2025-04-06T15:26:28.078+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/post-update.sample
[2025-04-06T15:26:28.079+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:28.080+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:28.081+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:28.082+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:28.082+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/pre-push.sample
[2025-04-06T15:26:28.083+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/hooks/pre-commit.sample
[2025-04-06T15:26:28.084+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/aarinmahala/.git/info/exclude
[2025-04-06T15:26:28.085+0000] {logging_mixin.py:188} WARNING - Processing aarinmahala: 18it [00:00, 310.83it/s]
[2025-04-06T15:26:28.086+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/aarinmahala
[2025-04-06T15:26:29.247+0000] {logging_mixin.py:188} WARNING - Processing webweather: 0it [00:00, ?it/s]
[2025-04-06T15:26:29.248+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/db.sqlite3
[2025-04-06T15:26:29.249+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.gitignore
[2025-04-06T15:26:29.252+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.255+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.258+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.259+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.260+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.260+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/LICENSE
[2025-04-06T15:26:29.263+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.267+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.270+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.271+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.271+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.275+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.279+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.282+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.282+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.283+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.285+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.288+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.291+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.292+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.292+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.295+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.298+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.301+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.301+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.302+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.305+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.308+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.312+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.313+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.313+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.314+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/urls.cpython-312.pyc
[2025-04-06T15:26:29.314+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/wsgi.cpython-39.pyc
[2025-04-06T15:26:29.315+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/settings.cpython-39.pyc
[2025-04-06T15:26:29.316+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/urls.cpython-39.pyc
[2025-04-06T15:26:29.317+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/wsgi.cpython-312.pyc
[2025-04-06T15:26:29.318+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/__init__.cpython-39.pyc
[2025-04-06T15:26:29.319+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/settings.cpython-312.pyc
[2025-04-06T15:26:29.319+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/projectweb/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.320+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/HEAD
[2025-04-06T15:26:29.321+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/index
[2025-04-06T15:26:29.321+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/packed-refs
[2025-04-06T15:26:29.322+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/description
[2025-04-06T15:26:29.322+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/config
[2025-04-06T15:26:29.323+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:29.323+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/refs/heads/main
[2025-04-06T15:26:29.324+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/logs/HEAD
[2025-04-06T15:26:29.324+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:29.325+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/logs/refs/heads/main
[2025-04-06T15:26:29.326+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/objects/pack/pack-a6965ce940aaddc172eda8c194a3519520120601.pack
[2025-04-06T15:26:29.327+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/objects/pack/pack-a6965ce940aaddc172eda8c194a3519520120601.idx
[2025-04-06T15:26:29.328+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/pre-receive.sample
[2025-04-06T15:26:29.328+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:29.329+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:29.330+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/commit-msg.sample
[2025-04-06T15:26:29.331+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:29.332+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/update.sample
[2025-04-06T15:26:29.332+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/post-update.sample
[2025-04-06T15:26:29.333+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:29.333+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:29.334+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:29.334+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:29.334+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/pre-push.sample
[2025-04-06T15:26:29.335+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/hooks/pre-commit.sample
[2025-04-06T15:26:29.336+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/.git/info/exclude
[2025-04-06T15:26:29.336+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/media/Hoang_Nguyen.jpg
[2025-04-06T15:26:29.337+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/media/mypic.JPG
[2025-04-06T15:26:29.338+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/media/media/mypic.JPG
[2025-04-06T15:26:29.338+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/media/media/4571485.png
[2025-04-06T15:26:29.339+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/media/media/mypic_iyzvX9z.JPG
[2025-04-06T15:26:29.341+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.344+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.347+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.348+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.348+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.351+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.354+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.358+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.359+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.360+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.361+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/API_KEY
[2025-04-06T15:26:29.365+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.368+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.371+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.372+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.373+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.376+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.379+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.383+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.384+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.385+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.388+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.392+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.395+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.396+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.397+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.400+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.405+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.409+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.410+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.410+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.414+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.417+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.421+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.422+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.422+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.423+0000] {logging_mixin.py:188} WARNING - Processing webweather: 23it [00:00, 131.34it/s]
[2025-04-06T15:26:29.426+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.429+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.431+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.432+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.433+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.434+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/migrations/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.435+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/__pycache__/apps.cpython-312.pyc
[2025-04-06T15:26:29.436+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/__pycache__/urls.cpython-312.pyc
[2025-04-06T15:26:29.436+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/__pycache__/models.cpython-312.pyc
[2025-04-06T15:26:29.437+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/__pycache__/admin.cpython-312.pyc
[2025-04-06T15:26:29.438+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/__pycache__/views.cpython-312.pyc
[2025-04-06T15:26:29.439+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.440+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/weather_app/static/js/weather.js
[2025-04-06T15:26:29.443+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.445+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.447+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.448+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.449+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.451+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.454+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.456+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.456+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.457+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.460+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.463+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.466+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.467+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.467+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.471+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.474+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.477+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.478+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.478+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.481+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.484+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.487+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.488+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.489+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.491+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.493+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.496+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.498+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.499+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.502+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.506+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.509+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.509+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.510+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.512+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.515+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.517+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.518+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.519+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.521+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.524+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.527+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.529+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.529+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.535+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.539+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.545+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.547+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.548+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.553+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.556+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.558+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.559+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.560+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.561+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/migrations/__pycache__/0001_initial.cpython-312.pyc
[2025-04-06T15:26:29.561+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/migrations/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.562+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/__pycache__/apps.cpython-312.pyc
[2025-04-06T15:26:29.563+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/__pycache__/urls.cpython-312.pyc
[2025-04-06T15:26:29.564+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/__pycache__/models.cpython-312.pyc
[2025-04-06T15:26:29.564+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/__pycache__/admin.cpython-312.pyc
[2025-04-06T15:26:29.565+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/__pycache__/views.cpython-312.pyc
[2025-04-06T15:26:29.565+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/project/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.570+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.573+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.577+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.578+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.579+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.583+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.587+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.593+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.594+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.597+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.598+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/Scripts/pip3.11.exe
[2025-04-06T15:26:29.601+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/Scripts/pip3.exe
[2025-04-06T15:26:29.604+0000] {logging_mixin.py:188} WARNING - Processing webweather: 37it [00:00, 99.23it/s] 
[2025-04-06T15:26:29.611+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.619+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.629+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.631+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.633+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.639+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.646+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.658+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.661+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.663+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.670+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.676+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.684+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.685+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.686+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.690+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.694+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.697+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.698+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.700+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.707+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.713+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.717+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.718+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.719+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.724+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.728+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.733+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.735+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.737+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.741+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.744+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.750+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.753+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.754+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.764+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.767+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.771+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.772+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.774+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.778+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.784+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.787+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.789+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.790+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.791+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/migrations/__pycache__/__init__.cpython-39.pyc
[2025-04-06T15:26:29.792+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/migrations/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.794+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/apps.cpython-312.pyc
[2025-04-06T15:26:29.796+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/urls.cpython-312.pyc
[2025-04-06T15:26:29.797+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/models.cpython-39.pyc
[2025-04-06T15:26:29.798+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/models.cpython-312.pyc
[2025-04-06T15:26:29.799+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/urls.cpython-39.pyc
[2025-04-06T15:26:29.805+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/admin.cpython-312.pyc
[2025-04-06T15:26:29.809+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/__init__.cpython-39.pyc
[2025-04-06T15:26:29.811+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/views.cpython-39.pyc
[2025-04-06T15:26:29.813+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/admin.cpython-39.pyc
[2025-04-06T15:26:29.814+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/views.cpython-312.pyc
[2025-04-06T15:26:29.815+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/form.cpython-312.pyc
[2025-04-06T15:26:29.817+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/apps.cpython-39.pyc
[2025-04-06T15:26:29.818+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:29.822+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.826+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.829+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.830+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.831+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.835+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.840+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.843+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.845+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.845+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.849+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.854+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.858+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.859+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.861+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.863+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap.css.map
[2025-04-06T15:26:29.865+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-grid.rtl.css.map
[2025-04-06T15:26:29.869+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.874+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.877+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.878+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.880+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.882+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-utilities.rtl.min.css.map
[2025-04-06T15:26:29.887+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.895+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.900+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.904+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.906+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.911+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-utilities.css.map
[2025-04-06T15:26:29.913+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-reboot.min.css.map
[2025-04-06T15:26:29.919+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.922+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.926+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.927+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.928+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.929+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap.rtl.min.css.map
[2025-04-06T15:26:29.935+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.948+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.952+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.953+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.954+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.958+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.962+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.965+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.966+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.967+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.968+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-reboot.css.map
[2025-04-06T15:26:29.972+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.975+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.979+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.981+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:29.981+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:29.996+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:29.999+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.002+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.003+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.004+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.016+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.026+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.039+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.043+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.045+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.047+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-utilities.min.css.map
[2025-04-06T15:26:30.049+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-grid.css.map
[2025-04-06T15:26:30.050+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap.min.css.map
[2025-04-06T15:26:30.052+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-utilities.rtl.css.map
[2025-04-06T15:26:30.056+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.059+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.062+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.063+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.064+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.065+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-reboot.rtl.min.css.map
[2025-04-06T15:26:30.068+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.071+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.076+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.077+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.078+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.082+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.090+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.094+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.095+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.096+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.097+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap.rtl.css.map
[2025-04-06T15:26:30.101+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.104+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.108+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.109+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.110+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.112+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.115+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.118+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.119+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.120+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.121+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-grid.min.css.map
[2025-04-06T15:26:30.122+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-reboot.rtl.css.map
[2025-04-06T15:26:30.123+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/css/bootstrap-grid.rtl.min.css.map
[2025-04-06T15:26:30.124+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/img/mypic.JPG
[2025-04-06T15:26:30.125+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.esm.min.js
[2025-04-06T15:26:30.125+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.min.js
[2025-04-06T15:26:30.126+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.min.js.map
[2025-04-06T15:26:30.127+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.bundle.js.map
[2025-04-06T15:26:30.128+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.bundle.min.js
[2025-04-06T15:26:30.132+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.esm.min.js.map
[2025-04-06T15:26:30.133+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.esm.js
[2025-04-06T15:26:30.134+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.bundle.min.js.map
[2025-04-06T15:26:30.136+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.js
[2025-04-06T15:26:30.138+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.bundle.js
[2025-04-06T15:26:30.139+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.js.map
[2025-04-06T15:26:30.140+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/home/static/js/bootstrap.esm.js.map
[2025-04-06T15:26:30.143+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.147+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.149+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.150+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.151+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.155+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.158+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.161+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.161+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.162+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.165+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.168+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.171+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.172+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.172+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.175+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.178+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.180+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.181+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.181+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.184+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.187+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.190+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.191+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.191+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.195+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.198+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.201+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.201+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.202+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.205+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.207+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.210+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.211+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.212+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.212+0000] {logging_mixin.py:188} WARNING - Processing webweather: 47it [00:00, 37.84it/s]
[2025-04-06T15:26:30.215+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.218+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.221+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.222+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.222+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.225+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.228+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.230+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.231+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.232+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.234+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.237+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.240+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.241+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.242+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.245+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.248+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.251+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.252+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.252+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.255+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.258+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.262+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.263+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.263+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.267+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.270+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.274+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.275+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.276+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.279+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.281+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.285+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.285+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.286+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.289+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.292+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.294+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.295+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.296+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.300+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.303+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.306+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.307+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.307+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.310+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.312+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.314+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.315+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.316+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.318+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.321+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.324+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.325+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.326+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.329+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.332+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.335+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.336+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.337+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.339+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.342+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.345+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.346+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.346+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.349+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.352+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.355+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.356+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.357+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.357+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0005_alter_post_image.cpython-312.pyc
[2025-04-06T15:26:30.358+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0006_alter_post_discription.cpython-312.pyc
[2025-04-06T15:26:30.358+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0002_post_modified_date.cpython-312.pyc
[2025-04-06T15:26:30.359+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/__init__.cpython-39.pyc
[2025-04-06T15:26:30.359+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0004_post_discription.cpython-312.pyc
[2025-04-06T15:26:30.360+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0001_initial.cpython-312.pyc
[2025-04-06T15:26:30.361+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0001_initial.cpython-39.pyc
[2025-04-06T15:26:30.361+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0003_post_image.cpython-312.pyc
[2025-04-06T15:26:30.362+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/0002_post_modified_date.cpython-39.pyc
[2025-04-06T15:26:30.363+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/migrations/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:30.363+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/apps.cpython-312.pyc
[2025-04-06T15:26:30.364+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/urls.cpython-312.pyc
[2025-04-06T15:26:30.364+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/models.cpython-39.pyc
[2025-04-06T15:26:30.365+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/models.cpython-312.pyc
[2025-04-06T15:26:30.365+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/urls.cpython-39.pyc
[2025-04-06T15:26:30.366+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/admin.cpython-312.pyc
[2025-04-06T15:26:30.366+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/__init__.cpython-39.pyc
[2025-04-06T15:26:30.367+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/views.cpython-39.pyc
[2025-04-06T15:26:30.367+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/admin.cpython-39.pyc
[2025-04-06T15:26:30.367+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/views.cpython-312.pyc
[2025-04-06T15:26:30.368+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/apps.cpython-39.pyc
[2025-04-06T15:26:30.368+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/webweather/blog/__pycache__/__init__.cpython-312.pyc
[2025-04-06T15:26:30.372+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.376+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.379+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.381+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.381+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.382+0000] {logging_mixin.py:188} WARNING - Processing webweather: 54it [00:01, 38.61it/s]
[2025-04-06T15:26:30.386+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.389+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.392+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.393+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.394+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.397+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.400+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.403+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:30.404+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:30.405+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:30.405+0000] {logging_mixin.py:188} WARNING - Processing webweather: 55it [00:01, 47.51it/s]
[2025-04-06T15:26:30.410+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/webweather
[2025-04-06T15:26:30.961+0000] {logging_mixin.py:188} WARNING - Processing skills: 0it [00:00, ?it/s]
[2025-04-06T15:26:30.963+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/README.md
[2025-04-06T15:26:30.964+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.gitignore
[2025-04-06T15:26:30.965+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.idea/material_theme_project_new.xml
[2025-04-06T15:26:30.966+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.idea/vcs.xml
[2025-04-06T15:26:30.968+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.idea/skills.iml
[2025-04-06T15:26:30.969+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.idea/.gitignore
[2025-04-06T15:26:30.970+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.idea/modules.xml
[2025-04-06T15:26:30.972+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/JS/scripts/AverageCalculator.js
[2025-04-06T15:26:30.973+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/JS/scripts/FrequencyCalculator.js
[2025-04-06T15:26:30.979+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/HEAD
[2025-04-06T15:26:30.980+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/index
[2025-04-06T15:26:30.981+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/packed-refs
[2025-04-06T15:26:30.982+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/description
[2025-04-06T15:26:30.983+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/config
[2025-04-06T15:26:30.985+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:30.986+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/refs/heads/main
[2025-04-06T15:26:30.987+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/logs/HEAD
[2025-04-06T15:26:30.988+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:30.993+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/logs/refs/heads/main
[2025-04-06T15:26:30.994+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/objects/pack/pack-2246a1f5eacd60ad0ae599fba19b557c9bfeb6ac.pack
[2025-04-06T15:26:30.995+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/objects/pack/pack-2246a1f5eacd60ad0ae599fba19b557c9bfeb6ac.idx
[2025-04-06T15:26:30.996+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/pre-receive.sample
[2025-04-06T15:26:30.997+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:30.998+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:30.999+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/commit-msg.sample
[2025-04-06T15:26:31.000+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:31.008+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/update.sample
[2025-04-06T15:26:31.009+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/post-update.sample
[2025-04-06T15:26:31.010+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:31.010+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:31.012+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:31.013+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:31.013+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/pre-push.sample
[2025-04-06T15:26:31.014+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/hooks/pre-commit.sample
[2025-04-06T15:26:31.015+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/skills/.git/info/exclude
[2025-04-06T15:26:31.016+0000] {logging_mixin.py:188} WARNING - Processing skills: 21it [00:00, 398.42it/s]
[2025-04-06T15:26:31.024+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/skills
[2025-04-06T15:26:31.025+0000] {logging_mixin.py:188} INFO - Repository CS50x-Coursework-Projects already cloned. Skipping.
[2025-04-06T15:26:33.285+0000] {logging_mixin.py:188} WARNING - Processing Bhasha-ai: 0it [00:00, ?it/s]
[2025-04-06T15:26:33.286+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/README.md
[2025-04-06T15:26:33.289+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.291+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.293+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.294+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.295+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.298+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.301+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.305+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.305+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.306+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.309+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/apis/uploads/dubbed/final/final_sample1.mp4
[2025-04-06T15:26:33.310+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/apis/uploads/subtitles/final/output.txt
[2025-04-06T15:26:33.312+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/apis/uploads/static/uploads/Student Testimonial - Varnika Chauhan (2).mp4
[2025-04-06T15:26:33.313+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/apis/uploads/static/uploads/a771a532-eeac-4018-8a54-0a99c6449a76.mp4
[2025-04-06T15:26:33.316+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/apis/uploads/static/uploads/Student Testimonial - Varnika Chauhan (1).mp4
[2025-04-06T15:26:33.317+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/apis/uploads/static/uploads/Student Testimonial - Varnika Chauhan.mp4
[2025-04-06T15:26:33.321+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.323+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.326+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.327+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.328+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.329+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/vite.config.js
[2025-04-06T15:26:33.329+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/README.md
[2025-04-06T15:26:33.330+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/.eslintrc.cjs
[2025-04-06T15:26:33.331+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/package.json
[2025-04-06T15:26:33.332+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/tailwind.config.js
[2025-04-06T15:26:33.333+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/.gitignore
[2025-04-06T15:26:33.334+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/postcss.config.js
[2025-04-06T15:26:33.335+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/package-lock.json
[2025-04-06T15:26:33.336+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/.vite/deps/_metadata.json
[2025-04-06T15:26:33.337+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/.vite/deps/package.json
[2025-04-06T15:26:33.338+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/main.jsx
[2025-04-06T15:26:33.342+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.345+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.348+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.349+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.349+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.350+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/App.jsx
[2025-04-06T15:26:33.351+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/store/auth.jsx
[2025-04-06T15:26:33.351+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/courses/Course.png
[2025-04-06T15:26:33.352+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/about/Company.gif
[2025-04-06T15:26:33.353+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/signup/Signup.gif
[2025-04-06T15:26:33.353+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/Download/Dubwithus.gif
[2025-04-06T15:26:33.354+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/Logo/parrot.png
[2025-04-06T15:26:33.354+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/Logo/Logo.png
[2025-04-06T15:26:33.355+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/chatbot/chatbox.svg
[2025-04-06T15:26:33.355+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/chatbot/message.svg
[2025-04-06T15:26:33.356+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/Payment/Fail.gif
[2025-04-06T15:26:33.356+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/Payment/Success.png
[2025-04-06T15:26:33.357+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/contact us/Contact.gif
[2025-04-06T15:26:33.357+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Assets/signin/login.gif
[2025-04-06T15:26:33.358+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Courses/ViewCourse.jsx
[2025-04-06T15:26:33.358+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Contact/Contact.jsx
[2025-04-06T15:26:33.359+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Download/Download.jsx
[2025-04-06T15:26:33.359+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Download/GetAllVideos.jsx
[2025-04-06T15:26:33.360+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Download/SubtitlesDownload.jsx
[2025-04-06T15:26:33.362+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.365+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.368+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.369+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.370+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.373+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.376+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.379+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.380+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.381+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.382+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Download/loader/Loader.jsx
[2025-04-06T15:26:33.385+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.388+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.393+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.395+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.396+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.397+0000] {logging_mixin.py:188} WARNING - Processing Bhasha-ai: 31it [00:00, 281.18it/s]
[2025-04-06T15:26:33.398+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/profile/ProfileComplete.jsx
[2025-04-06T15:26:33.398+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/profile/ProfileCard.jsx
[2025-04-06T15:26:33.399+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/About/About.jsx
[2025-04-06T15:26:33.400+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Uploads/Subtitles.jsx
[2025-04-06T15:26:33.400+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Uploads/Youtube.jsx
[2025-04-06T15:26:33.401+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Uploads/Dubbing.jsx
[2025-04-06T15:26:33.402+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Uploads/Notes.jsx
[2025-04-06T15:26:33.403+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Error/Error.jsx
[2025-04-06T15:26:33.404+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Admin/Admin.jsx
[2025-04-06T15:26:33.406+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Admin/AdminAuth.jsx
[2025-04-06T15:26:33.409+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Payment/Success.jsx
[2025-04-06T15:26:33.409+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Payment/Payment.jsx
[2025-04-06T15:26:33.410+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Payment/Fail.jsx
[2025-04-06T15:26:33.411+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Payment/Credit Card/Credit.jsx
[2025-04-06T15:26:33.414+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.417+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.420+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.421+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.421+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.422+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Auth/ProtectedRoute.jsx
[2025-04-06T15:26:33.423+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Auth/SignUp.jsx
[2025-04-06T15:26:33.423+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Auth/SignIn.jsx
[2025-04-06T15:26:33.424+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Pages/Landing/Landing.jsx
[2025-04-06T15:26:33.425+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Utils/Utils.jsx
[2025-04-06T15:26:33.428+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.432+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.435+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.436+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.437+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.438+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Chatbot/ChatMessage.jsx
[2025-04-06T15:26:33.438+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Chatbot/Chatbox.jsx
[2025-04-06T15:26:33.439+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Chatbot/Chatbot.jsx
[2025-04-06T15:26:33.440+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Commons/Footer.jsx
[2025-04-06T15:26:33.440+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Commons/Navbar.jsx
[2025-04-06T15:26:33.441+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Admin/GetCourse.jsx
[2025-04-06T15:26:33.442+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Admin/GetMessage.jsx
[2025-04-06T15:26:33.442+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Admin/GetUser.jsx
[2025-04-06T15:26:33.443+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Admin/EditUser.jsx
[2025-04-06T15:26:33.444+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Admin/AddCourseForm.jsx
[2025-04-06T15:26:33.445+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Card/UploadCards.jsx
[2025-04-06T15:26:33.445+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Card/Card.jsx
[2025-04-06T15:26:33.446+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Upload/UploadSubtitles.jsx
[2025-04-06T15:26:33.447+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Upload/UploadForm.jsx
[2025-04-06T15:26:33.448+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Upload/UploadsList.jsx
[2025-04-06T15:26:33.448+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Upload/UploadVideoYoutube.jsx
[2025-04-06T15:26:33.449+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Upload/UploadVideo.jsx
[2025-04-06T15:26:33.452+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.454+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.456+0000] {_metadata.py:139} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2025-04-06T15:26:33.457+0000] {_default.py:338} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-04-06T15:26:33.458+0000] {logging_mixin.py:188} INFO - Error initializing GCS client: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2025-04-06T15:26:33.458+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Upload/Document/Doc.jsx
[2025-04-06T15:26:33.459+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Landing/Pricing.jsx
[2025-04-06T15:26:33.460+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Landing/Testimonial.jsx
[2025-04-06T15:26:33.460+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Landing/Faqs.jsx
[2025-04-06T15:26:33.461+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Landing/Features.jsx
[2025-04-06T15:26:33.461+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/Components/Landing/Hero.jsx
[2025-04-06T15:26:33.462+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/client/src/config/contants.js
[2025-04-06T15:26:33.463+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/HEAD
[2025-04-06T15:26:33.463+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/index
[2025-04-06T15:26:33.464+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/packed-refs
[2025-04-06T15:26:33.465+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/description
[2025-04-06T15:26:33.465+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/config
[2025-04-06T15:26:33.466+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/refs/remotes/origin/HEAD
[2025-04-06T15:26:33.466+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/refs/heads/main
[2025-04-06T15:26:33.467+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/logs/HEAD
[2025-04-06T15:26:33.467+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/logs/refs/remotes/origin/HEAD
[2025-04-06T15:26:33.468+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/logs/refs/heads/main
[2025-04-06T15:26:33.473+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/objects/pack/pack-53f248984014eb87c7e6ef14e35cd444b9dec1a1.pack
[2025-04-06T15:26:33.474+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/objects/pack/pack-53f248984014eb87c7e6ef14e35cd444b9dec1a1.idx
[2025-04-06T15:26:33.475+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/pre-receive.sample
[2025-04-06T15:26:33.476+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/fsmonitor-watchman.sample
[2025-04-06T15:26:33.476+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/push-to-checkout.sample
[2025-04-06T15:26:33.476+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/commit-msg.sample
[2025-04-06T15:26:33.477+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/pre-rebase.sample
[2025-04-06T15:26:33.477+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/update.sample
[2025-04-06T15:26:33.477+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/post-update.sample
[2025-04-06T15:26:33.478+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/pre-merge-commit.sample
[2025-04-06T15:26:33.478+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/prepare-commit-msg.sample
[2025-04-06T15:26:33.478+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/pre-applypatch.sample
[2025-04-06T15:26:33.479+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/applypatch-msg.sample
[2025-04-06T15:26:33.479+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/pre-push.sample
[2025-04-06T15:26:33.479+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/hooks/pre-commit.sample
[2025-04-06T15:26:33.480+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/.git/info/exclude
[2025-04-06T15:26:33.480+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/package.json
[2025-04-06T15:26:33.481+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/.gitignore
[2025-04-06T15:26:33.482+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/server.js
[2025-04-06T15:26:33.482+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/package-lock.json
[2025-04-06T15:26:33.483+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/vercel.json
[2025-04-06T15:26:33.484+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/.env
[2025-04-06T15:26:33.485+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/payment/paymentRoutes.js
[2025-04-06T15:26:33.485+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/course/courseRoute.js
[2025-04-06T15:26:33.486+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/Subscription/subscriptionRouter.js
[2025-04-06T15:26:33.486+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/contact/contactRouter.js
[2025-04-06T15:26:33.487+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/media/media.js
[2025-04-06T15:26:33.487+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/Profile/profileRouter.js
[2025-04-06T15:26:33.488+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/Admin/admin.js
[2025-04-06T15:26:33.488+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/email/email-router.js
[2025-04-06T15:26:33.489+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/router/Auth/authRouter.js
[2025-04-06T15:26:33.489+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/payment/paymentController.js
[2025-04-06T15:26:33.490+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/Media/mediaController.js
[2025-04-06T15:26:33.490+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/course/courseController.js
[2025-04-06T15:26:33.491+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/profile/profileController.js
[2025-04-06T15:26:33.491+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/Subscription/subscriptionController.js
[2025-04-06T15:26:33.492+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/contact/contactController.js
[2025-04-06T15:26:33.492+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/Admin/adminController.js
[2025-04-06T15:26:33.493+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/email/email-controller.js
[2025-04-06T15:26:33.493+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/controller/Auth/authController.js
[2025-04-06T15:26:33.494+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/utils/db.js
[2025-04-06T15:26:33.494+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/models/course/courseModel.js
[2025-04-06T15:26:33.495+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/models/profile/profileModel.js
[2025-04-06T15:26:33.496+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/models/Subscription/subscritionModel.js
[2025-04-06T15:26:33.497+0000] {logging_mixin.py:188} WARNING - Processing Bhasha-ai: 93it [00:00, 471.67it/s]
[2025-04-06T15:26:33.498+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/models/contact/contactModel.js
[2025-04-06T15:26:33.499+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/models/media/Media.js
[2025-04-06T15:26:33.500+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/models/Auth/userModel.js
[2025-04-06T15:26:33.500+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/validators/auth-validator.js
[2025-04-06T15:26:33.501+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/api/index.js
[2025-04-06T15:26:33.501+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/middlewares/validate-middleware.js
[2025-04-06T15:26:33.502+0000] {logging_mixin.py:188} INFO - Deleted unneeded file: /tmp/Bhasha-ai/server/middlewares/authMiddleware.js
[2025-04-06T15:26:33.503+0000] {logging_mixin.py:188} WARNING - Processing Bhasha-ai: 99it [00:00, 457.39it/s]
[2025-04-06T15:26:33.507+0000] {logging_mixin.py:188} INFO - Deleted temporary folder: /tmp/Bhasha-ai
[2025-04-06T15:26:33.508+0000] {logging_mixin.py:188} INFO - Data loading completed.
[2025-04-06T15:26:33.509+0000] {gcs_fileupload_dag.py:18} INFO - Done running data_loading.
[2025-04-06T15:26:33.510+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-06T15:26:33.526+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_file_upload_dag, task_id=run_data_loading, execution_date=20250406T151000, start_date=20250406T152027, end_date=20250406T152633
[2025-04-06T15:26:33.580+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-06T15:26:33.604+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
